# Based on: https://raw.githubusercontent.com/ansible/ansible-examples
# Here are variables related to the standalone JBoss installation

# AWS specific variables
ec2_access_key:
ec2_secret_key:
ec2_region: eu-west-1
ec2_zone:
ec2_keypair: ansible

# Red Hat Enterprise Linux 7.3 (HVM), SSD Volume Type
ec2_image: ami-02ace471
ec2_instance_type: t2.medium
ec2_security_group: fuse-demo
ec2_instance_count: 1
ec2_tag: fuse-demo
ec2_object_name_prefix: fuse_
ec2_hosts: all
wait_for_port: 22
