# Based on: https://raw.githubusercontent.com/ansible/ansible-examples

# AWS specific variables
ec2_access_key:
ec2_secret_key:
ec2_region: eu-west-1
ec2_zone:
ec2_keypair: ansible

# Red Hat Enterprise Linux 7.3 (HVM), SSD Volume Type
#ec2_image: ami-02ace471

# CentOS Linux 7, 1703_01
ec2_image: ami-0d063c6b

ec2_instance_type: t2.medium
ec2_security_group: fuse-fabric-demo
ec2_tag: fuse-fabric-default
ec2_object_name_prefix: fuse_
ec2_hosts: all
wait_for_port: 22

# Configure the AWS instances to create for this scenario
ec2_instances:
- name: "fuse-fabric-default-001"
  image: "{{ ec2_image }}"
  type: "{{ ec2_instance_type }}"
  tags: 
    fabric_role: root
    ansible_group: "fuse-fabric-default-master"
    type: "{{ ec2_instance_type }}"
    security_group: "{{ ec2_security_group }}"
    tag: "{{ ec2_tag }}"
  group: "{{ ec2_security_group }}"
  ssh_user: "centos"
- name: "fuse-fabric-default-002"
  image: "{{ ec2_image }}"
  type: "{{ ec2_instance_type }}"
  tags: 
    fabric_role: container
    ansible_group: "fuse-fabric-default-container"
    type: "{{ ec2_instance_type }}"
    security_group: "{{ ec2_security_group }}"
    tag: "{{ ec2_tag }}"
  group: "{{ ec2_security_group }}"
  ssh_user: "centos"



# Vars for Fuse
# Fuse Version and Patch
fuse:
  version: '6.3.0'
  patch: '187'

# Patch Fuse Version and Patch
fuse_patch:
  version: '6.3.0'
  patch: '262'

# OS User to install/execute Fuse
user:
  name: 'fuse'
  shell: '/bin/bash'
  homedir: 'True'

# OS Global Variables

# Java Home
java_home: /usr/lib/jvm/jre-1.8.0-openjdk

# Fuse Home
fuse_home: '/opt/fuse/latest-{{ esb_name }}'

# Backups Paths
fuse_backup_path: /opt/fuse/backup

# Fuse Administrative Users
fuse_users:
  admin:
    username: admin
    password: karaf
    roles:
      - admin
      - manager
      - viewer
      - Monitor
      - Operator
      - Maintainer
      - Deployer
      - Auditor
      - Administrator
      - SuperUser
  deployer:
    username: deployer
    password: deployer
    roles:
      - Deployer
  guest:
    username: guest
    password: guest
    roles:
      - viewer
  amq:
    username: amq
    password: karaf
    roles:
      - viewer
      - Administrator

# Network of Brokers Multicast
nob_multicast_name: default

# KahaDB persistence store
kahadb_directory: /opt/fuse/kahadb

## Setup for Applications and Bundles

fuse_client: '{{ fuse_home }}/bin/client -r 3 -d 10 -u {{ fuse_users.admin.username }} -p {{ fuse_users.admin.password }}'

# Applications Home
app_home: '/opt/fuse/applications'

# Maven Repository
#maven_repository_manager: http://nexus:8081/nexus/content/groups/public
