---
# PLAY - Provision EC2 instances suitable for JBoss Fuse
- name: Provision EC2 instances suitable for JBoss Fuse
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
  - group_vars/all.yaml

  tasks:
  - name: Create Security Group
    ec2_group:
      name: "{{ ec2_security_group }}"
      description: Security Group for JBoss Fuse servers
      region: "{{ ec2_region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8181
          to_port: 8181
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

  - name: Launch EC2 instances
    ec2:
      group: "{{ ec2_security_group }}"
      key_name: "{{ ec2_keypair }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      instance_tags: "{ 'ansible_group':'fuseservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'tag':'{{ ec2_tag }}' }"
      count: "{{ ec2_instance_count }}"
      wait: true
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started
    with_items: "{{ ec2.instances | default([]) }}"
      
  - debug: msg="EC2 Instances --- {{ ec2.instances }}"
